### ISSUE TITLE
Правки к ЛР 3

### ISSUE THREAD

**Issue by BakasaRus** [sonyanov/Web-Lab-6sem-server#1]
- [x] Убери <kbd>Tab</kbd>, забудь про эту кнопку при наборе кода;
- [x] Вынести подключение к БД в одну переменную окружения;
- [x] Разделить фронт и бэк (желательно оставить в репозитории только бэк);
- [x] 0 и 1 в качестве результата функции - такое се)))
- [x] `if(!req.query.lat && !req.query.lon)` поправить;
- [x] Ранний `return` при ошибках для уменьшения вложенности;
- [x] Две функции для получения погоды, как во второй ЛР;
- [x] Разбить маршруты на 2 файла;
- [x] При ошибках сервера кидать ошибку 500 [вот по этой инструкции](https://expressjs.com/ru/guide/error-handling.html).

**Comment by sonyanov** [comment]
Все исправила

**Comment by BakasaRus** [comment]
Рано радуешься:

- [x] Расставь точки с запятыми в коде;
- [x] Про ранний `return`. Вот это:  
```js
async create(response) {
    var result = true
    if(await this.contain(response)){
      result = false
      return result
    } 
    else{
      city.create({
        name: response.name,
        coord: {
          latitude: response.coord.lat,
          lontitude: response.coord.lon
        }
      })
      return result
    }
  }
```  
Можно переделать в штуку следующего вида для уменьшения вложенности:  
```js
async create(response) {
  if(await this.contain(response)){
    return false;
  }
  city.create({
    name: response.name,
    coord: {
      latitude: response.coord.lat,
      lontitude: response.coord.lon
    }
  });
  return true;
  }
}
```

Плюс не все прошлые пункты сделаны
